require:
  - rubocop-factory_bot
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - lib/active_outbox/generators/templates/migration.rb

Gemspec/RequireMFA:
  Enabled: false

Lint/DuplicateMethods:
  Exclude:
    - lib/active_outbox/configuration.rb

Metrics/MethodLength:
  Max: 12

RSpec/MultipleMemoizedHelpers:
  Max: 7

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false
