require:
  - rubocop-factory_bot
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - lib/generators/active_outbox/templates/*

Gemspec/RequireMFA:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 7

RSpec/FilePath:
  Exclude:
    - spec/lib/active_outbox/outboxable/*

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/lib/active_outbox/outboxable/*

Style/Documentation:
  Enabled: false
