require:
  - rubocop-factory_bot
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - lib/generators/active_outbox/templates/migration.rb

Gemspec/RequireMFA:
  Enabled: false

Metrics/MethodLength:
  Max: 12

RSpec/MultipleMemoizedHelpers:
  Max: 7

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false
