require:
  - rubocop-factory_bot
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - lib/generators/active_outbox/templates/migration.rb

Gemspec/RequireMFA:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 7

Style/Documentation:
  Enabled: false
