name: CI

on: push

jobs:
  rspec:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        version: ['3.0', 3.1, 3.2]
        experimental: [false]
        include:
          - version: head
            experimental: true
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      BUNDLE_GEMFILE: Gemfile
    name: "RSpec tests: Ruby ${{ matrix.version }}"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.version }}
      - name: Run tests on sqlite
        run: bundle exec rspec
      - name: Run tests on postgres
        run: bundle exec rspec
        env:
          POSTGRES_USER: postgres
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          ADAPTER: postgresql

