name: CI

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        version: [2.7, '3.0', 3.1, 3.2]
        experimental: [false]
        include:
          - version: head
            experimental: true
    env:
      BUNDLE_GEMFILE: Gemfile
    name: "RSpec tests: Ruby ${{ matrix.version }}"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.version }}
      - name: Run tests
        run: bundle exec rspec
